FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    gcc \
    g++ \
    make \
    m4 \
    csh \
    perl \
    git \
    wget \
    curl \
    unzip \
    libnetcdf-dev \
    libnetcdff-dev \
    netcdf-bin \
    mpich \
    libmpich-dev \
    libpng-dev \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /wrf-project

CMD ["/bin/bash"]
